-- Seed default configuration values per charter
-- All rates stored as basis points (万分比) or percentage integers
-- NOTE: In 002 multi-tenant, accounts and config are created per-family
-- at family creation time. This seed file no longer auto-creates them.
-- The config defaults below are kept as reference but not inserted here.

-- Default config values (inserted by family service at family creation):
-- split_ratio_a = 15
-- split_ratio_b = 30
-- split_ratio_c = 55
-- b_tier1_rate = 200
-- b_tier1_limit = 100000
-- b_tier2_rate = 120
-- b_tier3_rate = 30
-- c_annual_rate = 500
-- penalty_multiplier = 2
-- redemption_fee_rate = 10
-- wishlist_lock_months = 3
-- wishlist_valid_months = 12
-- b_suspend_months = 12
-- c_lock_age = 18
